"""
GmailMCPClient - Phase 4 integration with saksham-mcp-server.

https://github.com/saksham20189575/saksham-mcp-server

Creates Gmail drafts via POST /create_email_draft. The upstream server does not
send email automatically; send_draft() records the Gmail draft_id as success
(status draft_created) so the orchestrator can persist it as email_id.
"""
import os
import re
from datetime import datetime, timezone
from typing import Optional

import requests
from dotenv import load_dotenv
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from shared.mcp_config import resolve_mcp_server_url, use_direct_google
from shared import google_direct

from agent_debug import agent_log

load_dotenv()


class GmailMCPClient:
    """Client for saksham Gmail MCP with optional local .eml fallback."""

    def __init__(self, mcp_server_url: Optional[str] = None, allow_local_fallback: bool = False):
        self.mcp_url = resolve_mcp_server_url(mcp_server_url)
        env_fallback = os.getenv("GMAIL_ALLOW_LOCAL_FALLBACK", "").lower()
        self.allow_local_fallback = allow_local_fallback or env_fallback in {"1", "true", "yes"}
        self._available: Optional[bool] = None

    def create_draft(
        self,
        to: str,
        subject: str,
        body: str,
        html_body: Optional[str] = None,
    ) -> dict:
        """Create a Gmail draft through MCP, direct API, or local .eml fallback."""
        if use_direct_google():
            return self._create_draft_via_direct(to, subject, body, html_body)
        if self._is_mcp_available():
            return self._create_draft_via_mcp(to, subject, body, html_body)
        if self.allow_local_fallback:
            return self._create_local_draft(to, subject, body, html_body)
        raise ConnectionError(
            f"Gmail MCP server is unavailable at {self.mcp_url}. "
            "Start saksham-mcp-server (uvicorn server:app) or set GMAIL_ALLOW_LOCAL_FALLBACK=true."
        )

    def send_draft(self, draft_id: str) -> dict:
        """Confirm draft creation. saksham-mcp-server does not send mail."""
        if draft_id.startswith("local://"):
            return self._send_local_draft(draft_id)
        if use_direct_google():
            return {
                "message_id": draft_id,
                "status": "draft_created",
                "sent_at": datetime.now(timezone.utc).isoformat(),
            }
        if not self._is_mcp_available():
            raise ConnectionError(
                f"Gmail MCP server became unavailable before confirming draft {draft_id}."
            )
        return {
            "message_id": draft_id,
            "status": "draft_created",
            "sent_at": datetime.now(timezone.utc).isoformat(),
        }

    def _is_mcp_available(self) -> bool:
        if self._available is not None:
            return self._available
        try:
            response = requests.get(f"{self.mcp_url}/", timeout=3)
            self._available = response.status_code == 200
            agent_log(
                "gmail_client.py:_is_mcp_available",
                "health_check",
                {"mcp_url": self.mcp_url, "status_code": response.status_code, "available": self._available},
                hypothesis_id="H1",
            )
        except Exception as exc:
            self._available = False
            agent_log(
                "gmail_client.py:_is_mcp_available",
                "health_check_failed",
                {"mcp_url": self.mcp_url, "error_type": type(exc).__name__},
                hypothesis_id="H1",
            )
        return self._available

    @retry(
        retry=retry_if_exception_type(requests.RequestException),
        wait=wait_exponential(multiplier=1, min=1, max=4),
        stop=stop_after_attempt(3),
        reraise=True,
    )
    def _post_json(self, url: str, payload: dict, timeout: int = 60) -> dict:
        try:
            response = requests.post(url, json=payload, timeout=timeout)
            response.raise_for_status()
            return response.json() if response.content else {}
        except requests.exceptions.Timeout as exc:
            raise ConnectionError(
                f"MCP request timed out after {timeout}s at {url}. "
                "Ensure MCP was started with AUTO_APPROVE=true (scripts/start_mcp_server.ps1) "
                "and token.json exists (run python auth.py in MCPServer/saksham-mcp-server)."
            ) from exc

    def _create_draft_via_direct(
        self,
        to: str,
        subject: str,
        body: str,
        html_body: Optional[str],
    ) -> dict:
        email_body = body
        if html_body:
            email_body += (
                "\n\n---\n"
                "(HTML summary was generated by the analyzer; open the linked report for full formatting.)"
            )
        data = google_direct.create_email_draft(to, subject, email_body)
        if data.get("status") != "success":
            raise ValueError(
                data.get("message", "Gmail create draft failed")
                + (f": {data.get('details', '')}" if data.get("details") else "")
            )
        draft_id = data.get("draft_id")
        if not draft_id:
            raise ValueError("Gmail API response did not include draft_id")
        return {
            "draft_id": draft_id,
            "source": "gmail",
            "to": to,
            "subject": subject,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }

    def _create_draft_via_mcp(
        self,
        to: str,
        subject: str,
        body: str,
        html_body: Optional[str],
    ) -> dict:
        email_body = body
        if html_body:
            email_body += (
                "\n\n---\n"
                "(HTML summary was generated by the analyzer; open the linked report for full formatting.)"
            )

        try:
            data = self._post_json(
                f"{self.mcp_url}/create_email_draft",
                {"to": to, "subject": subject, "body": email_body},
                timeout=120,
            )
            agent_log(
                "gmail_client.py:_create_draft_via_mcp",
                "mcp_response",
                {
                    "status": data.get("status"),
                    "has_draft_id": bool(data.get("draft_id")),
                    "message_preview": (data.get("message") or "")[:120],
                },
                hypothesis_id="H2,H3,H5",
            )

            if data.get("status") == "rejected":
                agent_log(
                    "gmail_client.py:_create_draft_via_mcp",
                    "rejected",
                    {"message": data.get("message")},
                    hypothesis_id="H3",
                )
                raise RuntimeError(data.get("message", "create_email_draft rejected"))

            if data.get("status") != "success":
                raise ValueError(
                    data.get("message", "Gmail MCP create draft failed")
                    + (f": {data.get('details', '')}" if data.get("details") else "")
                )

            draft_id = data.get("draft_id")
            if not draft_id:
                raise ValueError("Gmail MCP response did not include draft_id")

            return {
                "draft_id": draft_id,
                "source": "gmail",
                "to": to,
                "subject": subject,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as exc:
            self._available = False
            agent_log(
                "gmail_client.py:_create_draft_via_mcp",
                "exception",
                {"error_type": type(exc).__name__, "allow_local_fallback": self.allow_local_fallback},
                hypothesis_id="H1,H2,H5",
            )
            if self.allow_local_fallback:
                print(f"  Gmail MCP error: {exc} - falling back to local draft")
                return self._create_local_draft(to, subject, body, html_body)
            raise

    def _create_local_draft(
        self,
        to: str,
        subject: str,
        body: str,
        html_body: Optional[str],
    ) -> dict:
        output_dir = os.path.join("phase-4", "test-results", "drafts")
        os.makedirs(output_dir, exist_ok=True)

        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        safe_subject = re.sub(r"[^\w\-]", "_", subject)[:60]
        filename = f"{timestamp}_{safe_subject}.eml"
        filepath = os.path.abspath(os.path.join(output_dir, filename))

        with open(filepath, "w", encoding="utf-8") as file:
            file.write(self._build_eml(to, subject, body, html_body))

        draft_id = f"local://{filepath}"
        print(f"  [LOCAL FALLBACK] Draft saved to: {filepath}")

        return {
            "draft_id": draft_id,
            "source": "local_file",
            "to": to,
            "subject": subject,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }

    def _send_local_draft(self, draft_id: str) -> dict:
        filepath = draft_id.replace("local://", "")
        print(f"  [LOCAL FALLBACK] Draft saved only, not sent: {filepath}")
        return {
            "message_id": None,
            "status": "draft_saved",
            "sent_at": datetime.now(timezone.utc).isoformat(),
        }

    def _build_eml(
        self,
        to: str,
        subject: str,
        body: str,
        html_body: Optional[str],
    ) -> str:
        timestamp = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
        lines = [
            "From: Groww Review Insights Analyzer <noreply@groww-insights.local>",
            f"To: {to}",
            f"Subject: {subject}",
            f"Date: {timestamp}",
            "MIME-Version: 1.0",
        ]

        if html_body:
            boundary = "----=_Part_GrowwInsights"
            lines += [
                f'Content-Type: multipart/alternative; boundary="{boundary}"',
                "",
                f"--{boundary}",
                "Content-Type: text/plain; charset=utf-8",
                "",
                body,
                "",
                f"--{boundary}",
                "Content-Type: text/html; charset=utf-8",
                "",
                html_body,
                "",
                f"--{boundary}--",
            ]
        else:
            lines += [
                "Content-Type: text/plain; charset=utf-8",
                "",
                body,
            ]

        return "\n".join(lines)


GmailClient = GmailMCPClient
