"""
Regenerate Docs/deliverables for the latest insights week:
  - weekly-pulse-<week>.md
  - weekly-pulse-<week>.html (print to PDF)
  - reviews-<week>-sample-redacted.csv
"""
from __future__ import annotations

import csv
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DELIV = ROOT / "Docs" / "deliverables"


def main() -> None:
    from shared.database import DatabaseManager
    from shared.groww_product_map import cluster_by_keywords

    db = DatabaseManager()
    try:
        ins = db.get_insights()
        if not ins:
            raise SystemExit("No insights in DB. Run: python run_phase2.py")
        week = ins["week"]
        reviews = db.get_reviews_by_source("google_play")
        themes = cluster_by_keywords(reviews)
        dist = db.get_rating_distribution()
        sent = ins.get("sentiment_summary") or {}
        pos, neg, neu = sent.get("positive", 0), sent.get("negative", 0), sent.get("neutral", 0)
        total_sent = pos + neg + neu or 1

        DELIV.mkdir(parents=True, exist_ok=True)
        md_name = f"weekly-pulse-{week}.md"
        html_name = f"weekly-pulse-{week}.html"
        csv_name = f"reviews-{week}-sample-redacted.csv"

        theme_rows = "\n".join(
            f"| {i} | **{t.name}** | {t.review_count} | {t.sentiment.value} |"
            for i, t in enumerate(themes[:5], 1)
        )
        quotes = ins.get("quotes") or []
        quote_md = ""
        for q in quotes[:3]:
            qt = (q.get("text") or "")[:200]
            quote_md += f'\n> "{qt}"  \n> — **{q.get("rating")}★**\n'

        actions = ins.get("actions") or []
        action_md = "\n".join(
            f'| **{(a.get("priority") or "medium").upper()}** | {a.get("description", "")} |'
            for a in actions[:3]
        )

        md = f"""# Weekly Pulse — Groww App Reviews — {week}

| | |
|---|---|
| **App** | `com.nextbillion.groww` |
| **Reviews analysed** | {ins.get("total_reviews_analysed", len(reviews))} |
| **Generated** | {ins.get("generated_at", "")[:10]} |

## Sentiment

| Positive | Negative | Neutral |
|----------|----------|---------|
| {pos} ({round(100*pos/total_sent)}%) | {neg} ({round(100*neg/total_sent)}%) | {neu} |

**Ratings:** """ + " · ".join(f"{dist.get(i,0)}×{i}★" for i in range(1, 6)) + f"""

## Top product areas

| # | Area | Reviews | Sentiment |
|---|------|--------:|-----------|
{theme_rows}

## User voices
{quote_md}

## Actions

| Priority | Action |
|----------|--------|
{action_md}

---
*Regenerated by scripts/export_weekly_deliverables.py*
"""
        (DELIV / md_name).write_text(md, encoding="utf-8")

        body = html.escape(md).replace("\n", "<br>\n")
        (DELIV / html_name).write_text(
            f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Weekly Pulse {week}</title>
<style>body{{font-family:Segoe UI,sans-serif;max-width:720px;margin:2rem auto;line-height:1.5;color:#0f172a}}
@media print{{body{{margin:1cm}}}}</style></head>
<body>{body}</body></html>""",
            encoding="utf-8",
        )

        with (DELIV / csv_name).open("w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["id_hash", "source", "rating", "date", "text_redacted", "processed"])
            for i, r in enumerate(reviews[:40]):
                text = (r.get("text") or "")[:120]
                if len(r.get("text") or "") > 120:
                    text += "…"
                w.writerow([f"review_{i+1:04d}", r.get("source"), r.get("rating"), (r.get("date") or "")[:10], text, r.get("processed")])

        print(f"Wrote {DELIV / md_name}")
        print(f"Wrote {DELIV / html_name}  (open → Print → PDF)")
        print(f"Wrote {DELIV / csv_name}")

        # Refresh bundled Streamlit seed (no secrets — reviews truncated in seed)
        seed_path = ROOT / "data" / "dashboard_seed.json"
        snap = db.get_dashboard_snapshot()
        from shared.week_over_week import compute_week_over_week

        snap["wow"] = compute_week_over_week(snap["insights"], snap.get("prior_insights"))
        seed_path.parent.mkdir(parents=True, exist_ok=True)
        seed_path.write_text(json.dumps(snap, indent=2, default=str), encoding="utf-8")
        print(f"Wrote {seed_path}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
